In [26]:
import pandas as pd
import numpy as np

In [3]:
# Show all columns
pd.set_option("display.max_columns", None)

In [18]:
psm = pd.read_csv('../data/psm.tsv', sep='\t')
psm.head(3)

,Spectrum,Spectrum File,Peptide,Modified Peptide,Extended Peptide,Prev AA,Next AA,Peptide Length,Charge,Retention,Observed Mass,Calibrated Observed Mass,Observed M/Z,Calibrated Observed M/Z,Calculated Peptide Mass,Calculated M/Z,Delta Mass,SpectralSim,RTScore,Expectation,Hyperscore,Nextscore,Probability,Qvalue,Number of Enzymatic Termini,Number of Missed Cleavages,Protein Start,Protein End,Intensity,Assigned Modifications,Observed Modifications,Purity,Is Decoy,Is Contaminant,Is Unique,Protein,Protein ID,Entry Name,Gene,Protein Description,Mapped Genes,Mapped Proteins,Parent Scan Number,Apex Retention Time,Apex Scan Number,Retention Time Start,Retention Time End,Retention Time FWHM,Traced Scans
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,interact-GR_LCL_2D_ETHCD_fr1_immunopeptidome.p...,APAPVQPPM,APAPVQPPM[147],PPVPASHI.APAPVQPPM.IRRDITFP,I,I,9,2,2486.9940,922.4579,922.4579,462.2362,462.2362,922.4582,462.2364,-0.0003,0.9781,27.6873,0.000128,31.237,31.237,0.8516,0.003983,0,0,1626,1634,140532.75,9M(15.9949),NaN,0.0,False,False,False,sp|O14497|ARI1A_HUMAN,O14497,ARI1A_HUMAN,ARID1A,AT-rich interactive domain-containing protein 1A,NaN,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,1031,2514.2070,1042,2432.6992,2592.3110,104.48000,4
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,interact-GR_LCL_2D_ETHCD_fr1_immunopeptidome.p...,IPPPPPPAM,IPPPPPPAM[147],SLEEILNS.IPPPPPPAM.TNEAGAPR,S,T,9,2,2497.8610,931.4842,931.4842,466.7494,466.7494,931.4836,466.7491,0.0006,0.9176,14.8279,0.088030,28.492,23.724,0.9540,0.002359,0,0,65,73,236538.17,9M(15.9949),NaN,0.0,False,False,False,sp|Q9NTJ3|SMC4_HUMAN,Q9NTJ3,SMC4_HUMAN,SMC4,Structural maintenance of chromosomes protein 4,PRR12,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",1031,2537.1372,1053,2432.6992,2821.8672,125.17901,10
2,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01067.01067.2,interact-GR_LCL_2D_ETHCD_fr1_immunopeptidome.p...,IPPPPPPAM,IPPPPPPAM[147],SLEEILNS.IPPPPPPAM.TNEAGAPR,S,T,9,2,2570.5938,931.4836,931.4836,466.7491,466.7491,931.4836,466.7491,0.0000,0.9060,13.6157,0.080560,28.442,25.169,0.9566,0.002325,0,0,65,73,93692.16,9M(15.9949),NaN,0.0,False,False,False,sp|Q9NTJ3|SMC4_HUMAN,Q9NTJ3,SMC4_HUMAN,SMC4,Structural maintenance of chromosomes protein 4,PRR12,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",1064,2592.3110,1075,2432.6992,2664.9570,125.17901,7

In [19]:
columns = [
    'Spectrum',	
    'Peptide', 
    'Peptide Length',
    'Protein ID', 
    'Protein',
    'Gene', 
    'Mapped Proteins', 
    'Hyperscore', 
    'Nextscore', 
    'Qvalue', 
    'Probability', 
    'Delta Mass', 
    'SpectralSim', 
    'RTScore',
    'Retention',
    'Intensity',  
    'Is Decoy', 
    'Is Contaminant']

In [20]:
psm = psm[columns]
psm.head()

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.9940,140532.75,False,False
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.8610,236538.17,False,False
2,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01067.01067.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.442,25.169,0.002325,0.9566,0.0000,0.9060,13.6157,2570.5938,93692.16,False,False
3,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01078.01078.2,SVDPTQTEY,9,O75534,sp|O75534|CSDE1_HUMAN,CSDE1,"sp|LIEPE-NOT-SPLICED-28;|O75534|CSDE1;607_615,...",33.696,17.646,0.003916,0.9018,0.0000,0.9081,43.2023,2593.6390,3305104.20,False,False
4,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01082.01082.3,FKDLGEEHFK,10,P02769,sp|P02769|ALBU_BOVIN,ALB,NaN,44.894,20.822,0.002359,0.9490,-0.0004,0.9042,43.3239,2600.9368,0.00,False,False

In [21]:
psm.shape

(16671, 18)

In [22]:
print(psm['Is Decoy'].value_counts())
print(psm['Is Contaminant'].value_counts())

Is Decoy
False    16671
Name: count, dtype: int64
Is Contaminant
False    16671
Name: count, dtype: int64

In [23]:
len(psm[psm['Mapped Proteins'].isna()])

2373

In [24]:
len(psm[psm['Protein'].isna()])

0

In [27]:
psm["DeltaScore"] = (
    psm["Hyperscore"]
    - psm["Nextscore"]
)
psm.head(2)

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.994,140532.75,False,False,0.000
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.861,236538.17,False,False,4.768

In [ ]:
def classify_row(row):

    protein = str(row["Protein"]) if pd.notna(row["Protein"]) else ""
    mapped = str(row["Mapped Proteins"]) if pd.notna(row["Mapped Proteins"]) else ""

    # join all hits
    all_hits = protein
    if mapped.strip():
        all_hits += "," + mapped

    has_spliced = "LIEPE-SPLICED" in all_hits
    has_not_spliced = "LIEPE-NOT-SPLICED" in all_hits

    has_swissprot = "sp|" in all_hits and not (
        all_hits.startswith("sp|LIEPE")
    )

    has_trembl = "tr|" in all_hits

    mapped_empty = mapped.strip() == ""

    # classification

    if has_spliced and not has_swissprot and not has_trembl and not has_not_spliced:
        return "Spliced_only"

    elif has_spliced and (has_swissprot or has_trembl or has_not_spliced):
        return "Spliced_with_alternative"

    elif has_not_spliced and not has_swissprot and not has_trembl:
        return "Liepe_not_spliced_only"

    elif has_swissprot and not has_spliced:
        return "Canonical"

    elif has_trembl and not has_swissprot and not has_spliced:
        return "TrEMBL_only"

    else:
        return "Other"


psm["Mapping_status"] = psm.apply(classify_row, axis=1)
psm.head(2)

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore,Mapping_status
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.994,140532.75,False,False,0.000,Canonical
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.861,236538.17,False,False,4.768,Canonical

In [29]:
def contains_spliced(text):
    return "LIEPE-SPLICED" in str(text)

def contains_not_spliced(text):
    return "LIEPE-NOT-SPLICED" in str(text)

def contains_trembl(text):
    return "tr|" in str(text)

def contains_real_swissprot(text):

    text = str(text)

    hits = [x.strip() for x in text.split(",")]

    for h in hits:

        if h.startswith("sp|LIEPE"):
            continue

        if h.startswith("sp|"):
            return True

    return False


combined = (
    psm["Protein"].fillna("")
    + ","
    + psm["Mapped Proteins"].fillna("")
)

psm["has_spliced"] = combined.apply(contains_spliced)
psm["has_not_spliced"] = combined.apply(contains_not_spliced)
psm["has_trembl"] = combined.apply(contains_trembl)
psm["has_swissprot"] = combined.apply(contains_real_swissprot)
psm["mapped_empty"] = (
    psm["Mapped Proteins"]
    .fillna("")
    .str.strip()
    .eq("")
)

psm.head(3)

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore,Mapping_status,has_spliced,has_not_spliced,has_trembl,has_swissprot,mapped_empty
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.9940,140532.75,False,False,0.000,Canonical,False,True,True,True,False
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.8610,236538.17,False,False,4.768,Canonical,False,True,True,True,False
2,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01067.01067.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.442,25.169,0.002325,0.9566,0.0000,0.9060,13.6157,2570.5938,93692.16,False,False,3.273,Canonical,False,True,True,True,False

In [30]:
summary = pd.crosstab(
    psm["has_spliced"],
    psm["has_swissprot"]
)

print(summary)

has_swissprot  False  True
has_spliced
False            297  15305
True             784    285

In [31]:
summary2 = pd.crosstab(
    psm["has_spliced"],
    psm["has_not_spliced"]
)

print(summary2)

has_not_spliced  False  True
has_spliced
False             4621  10981
True              1009     60

In [32]:
dup_peptides = (
    psm.groupby("Peptide")
       .size()
       .reset_index(name="n")
       .query("n > 1")
       .sort_values("n", ascending=False)
)

print(dup_peptides.head())

          Peptide   n
3762    KRFEGLTQR  33
7202    RRFGDKLNF  31
7391   RRISGVDRYY  30
485   APRLNSADRPM  27
8448    SDGASPIRY  27

In [34]:
dup_peptides.shape

(3240, 2)

In [36]:
psm["Mapping_status"].value_counts()

Mapping_status
Canonical                   12603
TrEMBL_only                  1819
Liepe_not_spliced_only       1180
Spliced_only                  783
Spliced_with_alternative      286
Name: count, dtype: int64

In [37]:
psm.to_csv("psm_labeled.tsv", sep="\t", index=False)