In [26]:
import pandas as pd
import numpy as np

In [52]:
# Show all columns
pd.set_option("display.max_columns", None)

In [53]:
psm = pd.read_csv('../data/psm.tsv', sep='\t')
psm.head(3)

,Spectrum,Spectrum File,Peptide,Modified Peptide,Extended Peptide,Prev AA,Next AA,Peptide Length,Charge,Retention,Observed Mass,Calibrated Observed Mass,Observed M/Z,Calibrated Observed M/Z,Calculated Peptide Mass,Calculated M/Z,Delta Mass,SpectralSim,RTScore,Expectation,Hyperscore,Nextscore,Probability,Qvalue,Number of Enzymatic Termini,Number of Missed Cleavages,Protein Start,Protein End,Intensity,Assigned Modifications,Observed Modifications,Purity,Is Decoy,Is Contaminant,Is Unique,Protein,Protein ID,Entry Name,Gene,Protein Description,Mapped Genes,Mapped Proteins,Parent Scan Number,Apex Retention Time,Apex Scan Number,Retention Time Start,Retention Time End,Retention Time FWHM,Traced Scans
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,interact-GR_LCL_2D_ETHCD_fr1_immunopeptidome.p...,APAPVQPPM,APAPVQPPM[147],PPVPASHI.APAPVQPPM.IRRDITFP,I,I,9,2,2486.9940,922.4579,922.4579,462.2362,462.2362,922.4582,462.2364,-0.0003,0.9781,27.6873,0.000128,31.237,31.237,0.8516,0.003983,0,0,1626,1634,140532.75,9M(15.9949),NaN,0.0,False,False,False,sp|O14497|ARI1A_HUMAN,O14497,ARI1A_HUMAN,ARID1A,AT-rich interactive domain-containing protein 1A,NaN,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,1031,2514.2070,1042,2432.6992,2592.3110,104.48000,4
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,interact-GR_LCL_2D_ETHCD_fr1_immunopeptidome.p...,IPPPPPPAM,IPPPPPPAM[147],SLEEILNS.IPPPPPPAM.TNEAGAPR,S,T,9,2,2497.8610,931.4842,931.4842,466.7494,466.7494,931.4836,466.7491,0.0006,0.9176,14.8279,0.088030,28.492,23.724,0.9540,0.002359,0,0,65,73,236538.17,9M(15.9949),NaN,0.0,False,False,False,sp|Q9NTJ3|SMC4_HUMAN,Q9NTJ3,SMC4_HUMAN,SMC4,Structural maintenance of chromosomes protein 4,PRR12,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",1031,2537.1372,1053,2432.6992,2821.8672,125.17901,10
2,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01067.01067.2,interact-GR_LCL_2D_ETHCD_fr1_immunopeptidome.p...,IPPPPPPAM,IPPPPPPAM[147],SLEEILNS.IPPPPPPAM.TNEAGAPR,S,T,9,2,2570.5938,931.4836,931.4836,466.7491,466.7491,931.4836,466.7491,0.0000,0.9060,13.6157,0.080560,28.442,25.169,0.9566,0.002325,0,0,65,73,93692.16,9M(15.9949),NaN,0.0,False,False,False,sp|Q9NTJ3|SMC4_HUMAN,Q9NTJ3,SMC4_HUMAN,SMC4,Structural maintenance of chromosomes protein 4,PRR12,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",1064,2592.3110,1075,2432.6992,2664.9570,125.17901,7

In [54]:
columns = [
    'Spectrum',	
    'Peptide', 
    'Peptide Length',
    'Protein ID', 
    'Protein',
    'Gene', 
    'Mapped Proteins', 
    'Hyperscore', 
    'Nextscore', 
    'Qvalue', 
    'Probability', 
    'Delta Mass', 
    'SpectralSim', 
    'RTScore',
    'Retention',
    'Intensity',  
    'Is Decoy', 
    'Is Contaminant']

In [55]:
psm = psm[columns]
psm.head()

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.9940,140532.75,False,False
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.8610,236538.17,False,False
2,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01067.01067.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.442,25.169,0.002325,0.9566,0.0000,0.9060,13.6157,2570.5938,93692.16,False,False
3,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01078.01078.2,SVDPTQTEY,9,O75534,sp|O75534|CSDE1_HUMAN,CSDE1,"sp|LIEPE-NOT-SPLICED-28;|O75534|CSDE1;607_615,...",33.696,17.646,0.003916,0.9018,0.0000,0.9081,43.2023,2593.6390,3305104.20,False,False
4,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01082.01082.3,FKDLGEEHFK,10,P02769,sp|P02769|ALBU_BOVIN,ALB,NaN,44.894,20.822,0.002359,0.9490,-0.0004,0.9042,43.3239,2600.9368,0.00,False,False

In [56]:
psm.shape

(16671, 18)

In [57]:
print(psm['Is Decoy'].value_counts())
print(psm['Is Contaminant'].value_counts())

Is Decoy
False    16671
Name: count, dtype: int64
Is Contaminant
False    16671
Name: count, dtype: int64

In [58]:
len(psm[psm['Mapped Proteins'].isna()])

2373

In [59]:
len(psm[psm['Protein'].isna()])

0

In [60]:
psm["DeltaScore"] = (
    psm["Hyperscore"]
    - psm["Nextscore"]
)
psm.head(2)

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.994,140532.75,False,False,0.000
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.861,236538.17,False,False,4.768

In [62]:
psm_filtered = psm.loc[psm.groupby('Peptide')['DeltaScore'].idxmax()]
psm_filtered.shape

(10748, 19)

In [ ]:
def classify_row(row):

    protein = str(row["Protein"]) if pd.notna(row["Protein"]) else ""
    mapped = str(row["Mapped Proteins"]) if pd.notna(row["Mapped Proteins"]) else ""

    # join all hits
    all_hits = protein
    if mapped.strip():
        all_hits += "," + mapped

    has_spliced = "LIEPE-SPLICED" in all_hits
    has_not_spliced = "LIEPE-NOT-SPLICED" in all_hits

    has_swissprot = "sp|" in all_hits and not (
        all_hits.startswith("sp|LIEPE")
    )

    has_trembl = "tr|" in all_hits

    mapped_empty = mapped.strip() == ""

    # classification

    if has_spliced and not has_swissprot and not has_trembl and not has_not_spliced:
        return "Spliced_only"

    elif has_spliced and (has_swissprot or has_trembl or has_not_spliced):
        return "Spliced_with_alternative"

    elif has_not_spliced and not has_swissprot and not has_trembl:
        return "Liepe_not_spliced_only"

    elif has_swissprot and not has_spliced:
        return "Canonical"

    elif has_trembl and not has_swissprot and not has_spliced:
        return "TrEMBL_only"

    else:
        return "Other"


psm["Mapping_status"] = psm.apply(classify_row, axis=1)
psm.head(2)

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore,Mapping_status
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.994,140532.75,False,False,0.000,Canonical
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.861,236538.17,False,False,4.768,Canonical

In [29]:
def contains_spliced(text):
    return "LIEPE-SPLICED" in str(text)

def contains_not_spliced(text):
    return "LIEPE-NOT-SPLICED" in str(text)

def contains_trembl(text):
    return "tr|" in str(text)

def contains_real_swissprot(text):

    text = str(text)

    hits = [x.strip() for x in text.split(",")]

    for h in hits:

        if h.startswith("sp|LIEPE"):
            continue

        if h.startswith("sp|"):
            return True

    return False


combined = (
    psm["Protein"].fillna("")
    + ","
    + psm["Mapped Proteins"].fillna("")
)

psm["has_spliced"] = combined.apply(contains_spliced)
psm["has_not_spliced"] = combined.apply(contains_not_spliced)
psm["has_trembl"] = combined.apply(contains_trembl)
psm["has_swissprot"] = combined.apply(contains_real_swissprot)
psm["mapped_empty"] = (
    psm["Mapped Proteins"]
    .fillna("")
    .str.strip()
    .eq("")
)

psm.head(3)

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore,Mapping_status,has_spliced,has_not_spliced,has_trembl,has_swissprot,mapped_empty
0,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01032.01032.2,APAPVQPPM,9,O14497,sp|O14497|ARI1A_HUMAN,ARID1A,sp|LIEPE-NOT-SPLICED-12;|O14497|ARI1A;1626_163...,31.237,31.237,0.003983,0.8516,-0.0003,0.9781,27.6873,2486.9940,140532.75,False,False,0.000,Canonical,False,True,True,True,False
1,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01036.01036.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.492,23.724,0.002359,0.9540,0.0006,0.9176,14.8279,2497.8610,236538.17,False,False,4.768,Canonical,False,True,True,True,False
2,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01067.01067.2,IPPPPPPAM,9,Q9NTJ3,sp|Q9NTJ3|SMC4_HUMAN,SMC4,"sp|LIEPE-NOT-SPLICED-13;|Q9NTJ3|SMC4;65_73, sp...",28.442,25.169,0.002325,0.9566,0.0000,0.9060,13.6157,2570.5938,93692.16,False,False,3.273,Canonical,False,True,True,True,False

In [30]:
summary = pd.crosstab(
    psm["has_spliced"],
    psm["has_swissprot"]
)

print(summary)

has_swissprot  False  True
has_spliced
False            297  15305
True             784    285

In [31]:
summary2 = pd.crosstab(
    psm["has_spliced"],
    psm["has_not_spliced"]
)

print(summary2)

has_not_spliced  False  True
has_spliced
False             4621  10981
True              1009     60

In [32]:
dup_peptides = (
    psm.groupby("Peptide")
       .size()
       .reset_index(name="n")
       .query("n > 1")
       .sort_values("n", ascending=False)
)

print(dup_peptides.head())

          Peptide   n
3762    KRFEGLTQR  33
7202    RRFGDKLNF  31
7391   RRISGVDRYY  30
485   APRLNSADRPM  27
8448    SDGASPIRY  27

In [34]:
dup_peptides.shape

(3240, 2)

In [36]:
psm["Mapping_status"].value_counts()

Mapping_status
Canonical                   12603
TrEMBL_only                  1819
Liepe_not_spliced_only       1180
Spliced_only                  783
Spliced_with_alternative      286
Name: count, dtype: int64

In [37]:
psm.to_csv("psm_labeled.tsv", sep="\t", index=False)

In [40]:
psm.loc[
    psm['Protein ID'].str.contains('LIEPE-NOT-SPLICED', na=False)
    & (psm['Mapping_status'] == 'Canonical')
]

Empty DataFrame
Columns: [Spectrum, Peptide, Peptide Length, Protein ID, Protein, Gene, Mapped Proteins, Hyperscore, Nextscore, Qvalue, Probability, Delta Mass, SpectralSim, RTScore, Retention, Intensity, Is Decoy, Is Contaminant, DeltaScore, Mapping_status, has_spliced, has_not_spliced, has_trembl, has_swissprot, mapped_empty]
Index: []

In [39]:
psm.loc[
    psm['Protein ID'].str.contains('LIEPE-NOT-SPLICED', na=False)
    & (psm['Mapping_status'] == 'TrEMBL_only')
]

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore,Mapping_status,has_spliced,has_not_spliced,has_trembl,has_swissprot,mapped_empty
17,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01252.01252.2,ATEESDLAQQY,11,LIEPE-NOT-SPLICED-5358;,sp|LIEPE-NOT-SPLICED-5358;|P07237|PDIA1;84_94,NaN,"sp|P07237|PDIA1_HUMAN, tr|A0A7P0T8C0|A0A7P0T8C...",54.183,19.158,0.003638,0.9171,-0.0006,0.8841,27.3120,2931.9524,574400.200,False,False,35.025,TrEMBL_only,False,True,True,True,False
59,GR_LCL_2D_ETHCD_fr1_immunopeptidome.01813.01813.2,QSDLTTLTSAAY,12,LIEPE-NOT-SPLICED-6287;,sp|LIEPE-NOT-SPLICED-6287;|Q13227|GPS2;105_116,NaN,"sp|Q13227|GPS2_HUMAN, tr|I3L3Y9|I3L3Y9_HUMAN, ...",37.404,14.654,0.003916,0.9068,-0.0002,0.8054,24.5112,3941.8772,331323.470,False,False,22.750,TrEMBL_only,False,True,True,True,False
138,GR_LCL_2D_ETHCD_fr2_immunopeptidome.01164.01164.2,AVSTPNTPR,9,LIEPE-NOT-SPLICED-178;,sp|LIEPE-NOT-SPLICED-178;|Q9Y5W7|SNX14;552_560,NaN,"sp|Q9Y5W7|SNX14_HUMAN, tr|A0A804HI30|A0A804HI3...",19.880,13.519,0.000000,0.9997,-0.0001,0.9782,0.2692,2193.7310,14751.281,False,False,6.361,TrEMBL_only,False,True,True,True,False
139,GR_LCL_2D_ETHCD_fr2_immunopeptidome.01173.01173.2,VPRTVSSTTA,10,LIEPE-NOT-SPLICED-3846;,sp|LIEPE-NOT-SPLICED-3846;|Q15398|DLGP5;216_225,NaN,"sp|Q15398|DLGP5_HUMAN, tr|G3V4E5|G3V4E5_HUMAN",28.696,17.863,0.000161,0.9996,-0.0001,0.9142,1.7609,2215.9590,8780.509,False,False,10.833,TrEMBL_only,False,True,True,True,False
147,GR_LCL_2D_ETHCD_fr2_immunopeptidome.01211.01211.2,TPSGDKTSL,9,LIEPE-NOT-SPLICED-94;,sp|LIEPE-NOT-SPLICED-94;|P08133|ANXA6;535_543,NaN,"sp|P08133|ANXA6_HUMAN, tr|A0A0S2Z377|A0A0S2Z37...",32.843,16.587,0.000000,0.9997,0.0001,0.9539,0.9342,2312.5256,28010.727,False,False,16.256,TrEMBL_only,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16538,GR_LCL_2D_ETHCD_fr9_immunopeptidome.02517.02517.2,APRKPDWDL,9,LIEPE-NOT-SPLICED-2367;,sp|LIEPE-NOT-SPLICED-2367;|Q8WUD4|CCD12;108_116,NaN,"sp|Q8WUD4|CCD12_HUMAN, tr|A0ABB0MVG9|A0ABB0MVG...",28.559,16.510,0.000000,1.0000,0.0002,0.9582,19.0567,4265.4062,0.000,False,False,12.049,TrEMBL_only,False,True,True,True,False
16555,GR_LCL_2D_ETHCD_fr9_immunopeptidome.02547.02547.3,RRFVNVVPTFGK,12,LIEPE-NOT-SPLICED-6523;,sp|LIEPE-NOT-SPLICED-6523;|P62861|RS30;40_51,NaN,"sp|P62861|RS30_HUMAN, tr|E9PR30|E9PR30_HUMAN",53.469,16.053,0.000000,1.0000,-0.0024,0.8733,17.8273,4339.1675,310067.620,False,False,37.416,TrEMBL_only,False,True,True,True,False
16563,GR_LCL_2D_ETHCD_fr9_immunopeptidome.02561.02561.3,RRRSSVAFF,9,LIEPE-NOT-SPLICED-3692;,sp|LIEPE-NOT-SPLICED-3692;|O15297|PPM1D;93_101,NaN,"sp|O15297|PPM1D_HUMAN, tr|A0A0S2Z4W0|A0A0S2Z4W...",28.113,17.184,0.001190,0.9903,0.0003,0.9773,17.3349,4368.7160,117897.970,False,False,10.929,TrEMBL_only,False,True,True,True,False
16620,GR_LCL_2D_ETHCD_fr9_immunopeptidome.02696.02696.3,GRLTKHTKF,9,LIEPE-NOT-SPLICED-3676;,sp|LIEPE-NOT-SPLICED-3676;|Q9Y3U8|RL36;31_39,NaN,"sp|Q9Y3U8|RL36_HUMAN, tr|J3QSB5|J3QSB5_HUMAN",32.338,12.912,0.000161,0.9992,0.0015,0.8783,34.0109,4686.9517,43065.516,False,False,19.426,TrEMBL_only,False,True,True,True,False
16659,GR_LCL_2D_ETHCD_fr9_immunopeptidome.02939.02939.3,GRLTKHTKF,9,LIEPE-NOT-SPLICED-3676;,sp|LIEPE-NOT-SPLICED-3676;|Q9Y3U8|RL36;31_39,NaN,"sp|Q9Y3U8|RL36_HUMAN, tr|J3QSB5|J3QSB5_HUMAN",37.159,16.254,0.001882,0.9789,0.0013,0.8692,40.4053,5070.6123,343794.600,False,False,20.905,TrEMBL_only,False,True,True,True,False

In [48]:
spliced_rows = psm['Protein ID'].str.contains('LIEPE-SPLICED', na=False).sum()

not_spliced_rows = psm['Protein ID'].str.contains('LIEPE-NOT-SPLICED', na=False).sum()

no_liepe_rows = (~psm['Protein ID'].str.contains('LIEPE-', na=False)).sum()

print('Slpiced', spliced_rows)
print('Not spliced', not_spliced_rows)
print('No liepe', no_liepe_rows)

Slpiced 819
Not spliced 2810
No liepe 13042

In [44]:
len(psm['Peptide'].unique())

10748

In [47]:
len(psm['Spectrum'].unique())

16671

In [49]:
spliced_rows = psm['Protein'].str.contains('LIEPE-SPLICED', na=False).sum()

not_spliced_rows = psm['Protein'].str.contains('LIEPE-NOT-SPLICED', na=False).sum()

no_liepe_rows = (~psm['Protein'].str.contains('LIEPE-', na=False)).sum()

print('Slpiced', spliced_rows)
print('Not spliced', not_spliced_rows)
print('No liepe', no_liepe_rows)

Slpiced 819
Not spliced 2810
No liepe 13042

In [63]:
spliced_rows = psm_filtered['Protein'].str.contains('LIEPE-SPLICED', na=False).sum()

not_spliced_rows = psm_filtered['Protein'].str.contains('LIEPE-NOT-SPLICED', na=False).sum()

no_liepe_rows = (~psm_filtered['Protein'].str.contains('LIEPE-', na=False)).sum()

print('Filtered PSM')
print('Slpiced', spliced_rows)
print('Not spliced', not_spliced_rows)
print('No liepe', no_liepe_rows)

Filtered PSM
Slpiced 595
Not spliced 1592
No liepe 8561

In [50]:
psm.shape

(16671, 25)

In [51]:
peptide_df = pd.read_csv('../data/peptide.tsv', sep='\t')
peptide_df.shape

(10748, 20)

In [65]:
def classify_row_with_first_hit_priority(row):

    protein = str(row["Protein"]) if pd.notna(row["Protein"]) else ""
    mapped = str(row["Mapped Proteins"]) if pd.notna(row["Mapped Proteins"]) else ""

    # join all hits
    is_spliced = "LIEPE-SPLICED" in protein
    is_not_spliced = "LIEPE-NOT-SPLICED" in protein
    is_swissprot = "sp|" in protein and not (
        protein.startswith("sp|LIEPE")
    )
    is_trembl = "tr|" in protein

    mapped_empty = pd.isna(mapped) or str(mapped).strip() == ""
    mapped_spliced = "LIEPE-SPLICED" in mapped
    mapped_not_spliced = "LIEPE-NOT-SPLICED" in mapped
    mapped_swissprot = "sp|" in mapped and not (
        mapped.startswith("sp|LIEPE")
    )
    mapped_trembl = "tr|" in mapped


    # classification
    if is_not_spliced:
        return "Liepe_not_spliced"
    elif is_swissprot:
        return "Swiss-Prot"
    elif is_trembl:
        return "TrEMBL"
    elif is_spliced:
        if mapped_empty:
            return "Spliced_only"
        elif mapped_spliced and not mapped_swissprot and not mapped_trembl:
            return "Spliced_with_LIEPE-SPLICED_alternative"
        elif mapped_not_spliced and not mapped_swissprot and not mapped_trembl:
            return "Spliced_with_LIEPE-NOT-SPLICED_alternative"
        elif mapped_swissprot and not mapped_spliced and not mapped_not_spliced and not mapped_trembl:
            return "Spliced_with_Swiss-Prot_alternative"
        elif mapped_trembl and not mapped_spliced and not mapped_not_spliced and not mapped_swissprot:
            return "Spliced_with_TrEMBL_alternative"
        elif mapped_swissprot and mapped_trembl and not mapped_spliced and not mapped_not_spliced:
            return "Spliced_with_Uniprot_alternative"
        else:
            return "Spliced_with_alternative"
    else:
        return "Other"

In [66]:
psm_filtered["Class"] = psm_filtered.apply(classify_row_with_first_hit_priority, axis=1)
psm_filtered.head(15)

,Spectrum,Peptide,Peptide Length,Protein ID,Protein,Gene,Mapped Proteins,Hyperscore,Nextscore,Qvalue,Probability,Delta Mass,SpectralSim,RTScore,Retention,Intensity,Is Decoy,Is Contaminant,DeltaScore,Class
791,GR_LCL_2D_ETHCD_fr2_immunopeptidome.02619.02619.2,AAAAGRIAI,9,P26599,sp|P26599|PTBP1_HUMAN,PTBP1,"tr|A0A087WTS6|A0A087WTS6_HUMAN, tr|A0A087WU68|...",30.797,24.737,0.001760,0.9805,-0.0014,0.9888,7.8471,3856.5366,770104.20,False,False,6.060,Swiss-Prot
1827,GR_LCL_2D_ETHCD_fr2_immunopeptidome.04745.04745.2,AAAEPKLFGGF,11,P12931,sp|P12931|SRC_HUMAN,SRC,"sp|LIEPE-NOT-SPLICED-5388;|P12931|SRC;57_67, t...",46.747,18.599,0.000000,0.9999,0.0001,0.9456,5.1007,5801.0510,306523.25,False,False,28.148,Swiss-Prot
16347,GR_LCL_2D_ETHCD_fr9_immunopeptidome.02090.02090.3,AAAMTDNTNVNY,12,Q9BYV7,sp|Q9BYV7|BCDO2_HUMAN,BCO2,NaN,22.147,14.416,0.001339,0.9900,0.0081,0.4576,0.7580,3401.9424,205642.30,False,False,7.731,Swiss-Prot
5647,GR_LCL_2D_ETHCD_fr4_immunopeptidome.03495.03495.2,AACSKFFYK,9,LIEPE-SPLICED-2050;,sp|LIEPE-SPLICED-2050;|P52739|ZN131;42_42_53_61,NaN,"sp|P52739|ZN131_HUMAN, tr|D6R9I2|D6R9I2_HUMAN,...",36.426,16.989,0.000000,0.9999,-0.0004,0.9295,3.0824,3948.8389,1458379.50,False,False,19.437,Spliced_with_Uniprot_alternative
1304,GR_LCL_2D_ETHCD_fr2_immunopeptidome.03610.03610.2,AAFAYTVKY,9,Q8N2K1,sp|Q8N2K1|UB2J2_HUMAN,UBE2J2,tr|A6NGS0|A6NGS0_HUMAN,44.771,19.802,0.000000,1.0000,-0.0004,0.8891,0.8176,4614.6870,1583053.50,False,False,24.969,Swiss-Prot
1724,GR_LCL_2D_ETHCD_fr2_immunopeptidome.04464.04464.2,AAFPGASLY,9,Q15038,sp|Q15038|DAZP2_HUMAN,DAZAP2,"tr|F8VUW5|F8VUW5_HUMAN, tr|S4R3Q0|S4R3Q0_HUMAN",22.563,17.693,0.001405,0.9895,-0.0006,0.8823,0.8709,5440.7886,1739853.60,False,False,4.870,Swiss-Prot
6793,GR_LCL_2D_ETHCD_fr4_immunopeptidome.05438.05438.2,AAFPKKLAF,9,O75396,sp|O75396|SC22B_HUMAN,SEC22B,NaN,29.444,16.113,0.000000,0.9999,0.0005,0.9258,0.6661,5252.0810,1288046.00,False,False,13.331,Swiss-Prot
5307,GR_LCL_2D_ETHCD_fr4_immunopeptidome.02911.02911.2,AAKLEPKSF,9,Q99805,sp|Q99805|TM9S2_HUMAN,TM9SF2,sp|LIEPE-NOT-SPLICED-1387;|Q99805|TM9S2;232_240,36.979,20.144,0.000000,0.9998,-0.0015,0.9400,0.0502,3625.9910,1362683.60,False,False,16.835,Swiss-Prot
4562,GR_LCL_2D_ETHCD_fr4_immunopeptidome.01610.01610.2,AAKPHNPGF,9,Q12906,sp|Q12906|ILF3_HUMAN,ILF3,sp|LIEPE-NOT-SPLICED-1267;|Q12906|ILF3;615_623...,31.911,10.009,0.000000,1.0000,-0.0013,0.8873,2.3525,2911.1345,2351089.80,False,False,21.902,Swiss-Prot
1394,GR_LCL_2D_ETHCD_fr2_immunopeptidome.03789.03789.2,AAMLDTVVFK,10,LIEPE-NOT-SPLICED-3922;,sp|LIEPE-NOT-SPLICED-3922;|O00487|PSDE;301_310,NaN,sp|O00487|PSDE_HUMAN,40.120,40.120,0.000000,1.0000,-0.0012,0.8646,2.4535,4777.2830,612916.20,False,False,0.000,Liepe_not_spliced
3701,GR_LCL_2D_ETHCD_fr3_immunopeptidome.04783.04783.2,AANPHSFVF,9,Q9NQ55,sp|Q9NQ55|SSF1_HUMAN,PPAN,"sp|LIEPE-NOT-SPLICED-716;|Q9NQ55|SSF1;26_34, t...",21.217,10.670,0.000161,0.9996,-0.0003,0.8377,5.7286,5359.9224,11314225.00,False,False,10.547,Swiss-Prot
1785,GR_LCL_2D_ETHCD_fr2_immunopeptidome.04640.04640.2,AAQGEPQVQFKL,12,P62826,sp|P62826|RAN_HUMAN,RAN,tr|B5MDF5|B5MDF5_HUMAN,55.163,23.352,0.000000,1.0000,-0.0004,0.9222,1.7349,5655.4200,1186063.40,False,False,31.811,Swiss-Prot
1469,GR_LCL_2D_ETHCD_fr2_immunopeptidome.03937.03937.2,AARAIISEL,9,P78344,sp|P78344|IF4G2_HUMAN,EIF4G2,sp|LIEPE-NOT-SPLICED-185;|P78344|IF4G2;647_655...,20.807,15.470,0.002325,0.9591,-0.0012,0.9299,4.9197,4916.4080,1194510.10,False,False,5.337,Swiss-Prot
3939,GR_LCL_2D_ETHCD_fr3_immunopeptidome.05278.05278.2,AARDFLQTF,9,Q9BT17,sp|Q9BT17|MTG1_HUMAN,MTG1,"sp|LIEPE-NOT-SPLICED-999;|Q9BT17|MTG1;301_309,...",26.093,18.859,0.000664,0.9926,-0.0007,0.9288,2.9442,5849.0300,706862.56,False,False,7.234,Swiss-Prot
8119,GR_LCL_2D_ETHCD_fr5_immunopeptidome.02912.02912.3,AARPKSAFDF,10,LIEPE-SPLICED-2260;,sp|LIEPE-SPLICED-2260;|Q9Y5V3|MAGD1;71_78_93_94,NaN,NaN,21.803,14.905,0.003916,0.9015,-0.0007,0.7156,19.3487,3821.4158,16672507.00,False,False,6.898,Spliced_only

In [67]:
psm_filtered["Class"].value_counts()

Class
Swiss-Prot                                    8250
Liepe_not_spliced                             1592
Spliced_only                                   554
TrEMBL                                         311
Spliced_with_Uniprot_alternative                19
Spliced_with_Swiss-Prot_alternative             15
Spliced_with_TrEMBL_alternative                  3
Spliced_with_LIEPE-SPLICED_alternative           3
Spliced_with_LIEPE-NOT-SPLICED_alternative       1
Name: count, dtype: int64

In [68]:
psm_filtered.to_csv("psm_filtered_classified.tsv", sep="\t", index=False)